 #####################################################################
 # Copyright (c) 2024 Boeing
 #
 # This program and the accompanying materials are made
 # available under the terms of the Eclipse Public License 2.0
 # which is available at https://www.eclipse.org/legal/epl-2.0/
 #
 # SPDX-License-Identifier: EPL-2.0
 #
 # Contributors:
 #     Boeing - initial API and implementation
 ######################################################################
[package]
name = "java_rust_ffi"
version = "0.1.0"
edition = "2021"
authors=["Jaden Puckett <jaden.w.puckett@boeing.com>"]
license.workspace=true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "java_rust_ffi"
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
nom = "7.1.3"
nom-bufreader = { version = "0.2.0" }
tracing = { version = "0.1.40" }
serde = { version = "1.0.188", optional = false, features = ["derive"] }
serde_json = "1.0.107"
applicability = {path="../applicability",features=["serde"]}
applicability_parser_types = {path="../applicability_parser_types"}
applicability_parser = {path="../applicability_parser",features=["serde"]}
applicability_parser_config = {path="../applicability_parser_config"}
applicability_substitution = {path="../applicability_substitution"}
applicability_sanitization = {path="../applicability_sanitization"}
jni = "0.21.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
mimalloc = "0.1.46"